### ISSUE TITLE
Improve UnitPriority

### ISSUE THREAD

**Issue by jeepee12** [RaphaelRoyerRivard/commandcenter#30]
Try to improve the "GetUnitPriority" function in MTCS. (src/UCTCDState.cpp)
Test with different values to find the best weights.
Also, try to explain the given value of 15.

**Comment by RaphaelRoyerRivard** [comment]
Pour le 15 je voulais juste que la priorité soit plus haute pour un
banneling que pour les zerglings (dps de 10 si je me souviens bien).

**Comment by wild006** [comment]
Le dps est fixé selon http://liquipedia.net/starcraft2/Damage_per_second. Done commit 64ed1a30c223b5a1823cd0b8eb69d78c13307c72
