### ISSUE TITLE
Be more intelligent on the continuous attack

### ISSUE THREAD

**Issue by jeepee12** [RaphaelRoyerRivard/commandcenter#38]
Find a way to retreat if we are sure to lose the battle. 2-3 marines vs 2-3 stalkers.

This is complex and relative.

**Comment by jeepee12** [comment]
Search for : bool Squad::needsToRegroup() const    in Squad.cpp         We only need to find a condition for regrouping.

**Comment by jeepee12** [comment]
I did just a minimum regroup condition.

**Comment by jeepee12** [comment]
To evaluate if we should retreat, we could count the known enemy army supply vs ours.

**Comment by jeepee12** [comment]
We can at least have a minimum number of units the enemy has (based on what we saw). And when we kill units, we deleted them from the minimum number.

**Comment by RaphaelRoyerRivard** [comment]
I added MicroManager::getUnitPower() that allow us to calculate the power a our units vs enemy units so be can back when it's too dangerous.
