### ISSUE TITLE
Evalutate if we can do something for canon rush

### ISSUE THREAD

**Issue by jeepee12** [RaphaelRoyerRivard/commandcenter#45]

**Comment by RaphaelRoyerRivard** [comment]
Peut être harass le probe avec un scv

**Comment by jeepee12** [comment]
Il faudrait surtout attack les pylons et canons construient dans notre base

**Comment by RaphaelRoyerRivard** [comment]
Oui mais ils arrivent avant qu'on ait des marines alors si on arrive à
empêcher le probe de les construire ça devrait régler le problème.

**Comment by jeepee12** [comment]
At least, we are attacking the canons now.

**Comment by jeepee12** [comment]
If we see a worker in our base, we attack it. Then, if we see an enemy unit or building we send two units on it (worker if we do not have combat unit) and for canons, we send 4 units.
