### ISSUE TITLE
Repeat the last item of the build order indefinitely

### ISSUE THREAD

**Issue by jeepee12** [RaphaelRoyerRivard/commandcenter#48]

**Comment by AntoineTheb** [comment]
Check avec Raph il l'avais fait la session passée je crois

**Comment by RaphaelRoyerRivard** [comment]
Ouais je l'avais fait mais Churchill a changé la manière de builder des
units pis j'ai cherché genre 15 min comment faire pour corriger ça sans
trouver. Mon ancien code est en commentaire dans la méthode
ProductionManager::manageBuildOrderQueue().

Raphaël Royer-Rivard


Le mar. 3 avr. 2018 à 16:25, Antoine Théberge <notifications@github.com> a
écrit :

**Comment by jeepee12** [comment]
Fixed in ladder_imrovements branch
